# --- REPLACE THESE TWO LINES WITH YOUR EXACT KEYS ---
sonar.projectKey=Anurag17K_ak-scp-travelogue-01
sonar.organization=anurag17k

# --- DO NOT CHANGE ANYTHING BELOW THIS LINE ---
sonar.python.version=3.12
sonar.sources=.

# Exclude folders that contain third-party code or database files
sonar.exclusions=**/migrations/**, travelogue/settings.py, travelogue/asgi.py, travelogue/wsgi.py, manage.py

# Tell SonarCloud where your tests are located (if you write unit tests later)
sonar.tests=.
sonar.test.inclusions=**/tests.py, **/test_*.py
sonar.python.coverage.reportPaths=coverage.xml