# Generated by Django 6.0.1 on 2026-03-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0002_journey_user_alter_journey_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
