# Generated by Django 6.0.1 on 2026-03-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0003_journey_latitude_journey_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
