# Generated by Django 6.0.1 on 2026-03-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0004_journey_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='theme',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='journey',
            name='trip_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
