# Generated by Django 6.0.1 on 2026-03-02 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0005_alter_journey_city_alter_journey_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='theme',
        ),
    ]
