# Generated by Django 4.2.29 on 2026-04-01 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0009_journeymedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journeymedia',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='journeymedia',
            name='longitude',
        ),
    ]
