name: Deploy Travelogue to AWS EB

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Elastic Beanstalk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create ZIP deployment package
        # Dives into the nested folder and zips the Django appsss
        run: |
          cd travelogue 
          zip -r ../deploy.zip . -x "db.sqlite3" "*/__pycache__/*"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          application_name: travelogue-app
          environment_name: travelogue-ebs-env
          version_label: "travelogue-${{ github.sha }}"
          region: us-east-1
          deployment_package: deploy.zip