"""
Django settings for travelogue project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/!!

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8#bq@m29zx0j0$s#c9o@pwfw8&l$nn5ozl(j5^735h=3e2(&6x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Tell Django it is safely behind a Cloudflare HTTPS proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Ensure cross-site request forgery (CSRF) tokens work through the proxy
CSRF_TRUSTED_ORIGINS = ['https://travelogue.anuragktech.me']

APPOINTMENT_API_BASE = "https://2o7jj4hez6.execute-api.us-east-1.amazonaws.com"
APPOINTMENT_API_KEY = "1c1a99f9-a3bb-4b35-bd73-fc72aa4d483f"
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'journeys',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'travelogue.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'travelogue.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.environ.get('DB_NAME', 'travelogue_db'),
#         'USER': os.environ.get('DB_USER', 'adminuser'),
#         'PASSWORD': os.environ.get('DB_PASSWORD', 'ADMINpassword'),
#         'HOST': os.environ.get('DB_HOST', 'shared-master-db.cuz4g626e6hn.us-east-1.rds.amazonaws.com'),
#         'PORT': os.environ.get('DB_PORT', '5432'),
#     }
# }


# 1. CI/CD Sandbox: If GitHub Actions is running this, use a fast local SQLite database
# if os.environ.get('GITHUB_ACTIONS') == 'true':
#     print("CI/CD Pipeline Detected: Using local SQLite database for tests.")
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.sqlite3',
#             'NAME': BASE_DIR / 'db.sqlite3',
#         }
#     }
# # 2. Production/Local: Otherwise, connect to your real AWS RDS Database
# else:
#     print("Standard Environment Detected: Using AWS RDS PostgreSQL.")
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.postgresql',
#             'NAME': os.environ.get('DB_NAME', 'travelogue_db'),
#             'USER': os.environ.get('DB_USER', 'adminuser'),
#             'PASSWORD': os.environ.get('DB_PASSWORD', 'ADMINpassword'),
#             'HOST': os.environ.get('DB_HOST', 'shared-master-db.cuz4g626e6hn.us-east-1.rds.amazonaws.com'),
#             'PORT': os.environ.get('DB_PORT', '5432'),
#         }
#     }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# --- AWS S3 Configuration ---
# Boto3 will automatically use your AllAccessEC2Role for authentication!
AWS_STORAGE_BUCKET_NAME = 'travelogue-media-bucket'
AWS_S3_REGION_NAME = 'us-east-1'

# Tell Django to use S3 for all user-uploaded media
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# --- SECURE COOKIES & HEADERS (OWASP ZAP FIXES) ---

# Ensures cookies are only sent over HTTPS 
# (Fixes: Cookie Without Secure Flag)
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Prevents JavaScript from reading the session cookie 
# (Fixes: Cookie No HttpOnly Flag)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

# Forces the browser to strictly use HTTPS for the next year
# (Fixes: Strict-Transport-Security Header Not Set)
SECURE_HSTS_SECONDS = 31536000 
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Prevents the browser from guessing the content type
# (Fixes: X-Content-Type-Options Header Missing)
SECURE_CONTENT_TYPE_NOSNIFF = True

# Defends against Clickjacking by preventing iframes
# (Fixes: X-Frame-Options warnings)
X_FRAME_OPTIONS = 'DENY'